name: Push Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - name: Send notification email
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com   
            server_port: 465                  
            username: ${{ secrets.EMAIL }}    
            password: ${{ secrets.PASSWORD }}  # fqan xzyv byzq gson
            subject: 'Push Notification'      
            body: 'Push Notification'
            to: ${{ vilayat.aliyev@code.edu.az  }}       
            from: ${{ secrets.EMAIL_FROM }} 